### ISSUE TITLE
Citadel Master Sheet

### ISSUE THREAD

**Issue by gbrann** [gbrann/EVEProductionSuite#11]
Create the Citadel Master Sheet for easy creation of Citadel Build Sheets

**Comment by gbrann** [comment]
Need to pull material data based on the dropdown for which citadel it is.

**Comment by gbrann** [comment]
Speaking of.. drop down selection of which station it is, does not change values on sheet.

**Comment by wytsa** [comment]
will fix that now

**Comment by gbrann** [comment]
Neg. Doesn't seem to be working. The only one showing values is Astrahus.

**Comment by gbrann** [comment]
Citadel Build Sheets COMPLETE! 💃
