### ISSUE TITLE
Template New Lines in all GESI pull tabs

### ISSUE THREAD

**Issue by gbrann** [gbrann/EVEProductionSuite#21]
Would like the VLOOKUP Name functions to auto populate on new rows that are added by the ESI. This would fix an issue where some assets, prints, etc might not show up due to the lack of the name lookup formula. 

Ref: https://productforums.google.com/forum/#!topic/docs/lZpA-egYvac

**Comment by gbrann** [comment]
@wytsa can you take a look at this and tell me what you think?

**Comment by gbrann** [comment]
@wytsa Any update?

**Comment by wytsa** [comment]
have input formulas to update the items in the column for 3 of the gesi tabs

**Comment by gbrann** [comment]
Formula changed to:

`=arrayformula(if(row(I:I),vlookup(H:H,VLOOKUP!A:B,2,false),IF(ISBLANK(H:H),"",""))`

**Comment by gbrann** [comment]
GESI-MARKET titles on Row 1 are manual, not ESI set. That row can be deleted.
