### ISSUE TITLE
Industry Jobs not showing up in Corporate Stock

### ISSUE THREAD

**Issue by gbrann** [gbrann/EVEProductionSuite#29]
Invalid vlookup formula on item name, was pulling from the wrong item ID, thus causing the lookup from Corporate Stock to show incorrect number of jobs. 

Formula in GESI-JOBS, column W should be: `=arrayformula(if(row(W:W),vlookup(R:R,VLOOKUP!A:B,2,false),IF(ISBLANK(D:D),"","")))`

Existing formula was as follows and pulled the blueprint ID not the Item ID of the product it was making.

**Comment by wytsa** [comment]
formula has been changed to the above.
