### ISSUE TITLE
Change Buyback for new AMC Style

### ISSUE THREAD

**Issue by gbrann** [gbrann/EVEProductionSuite#30]
The idea is simple, use weight and times to calculate the weekly buyback payouts to active miners. The sheet will be a backend where a simple Google Sites or Google Form is used to input the data into the sheet. The Sheet can then pull from Week Numbers to show who gets what paid out. 

I'm basing this on the AMC Buyback sheet. I want it to be simple and easy to use.

**Comment by gbrann** [comment]
Added Gases, Moon, Compressed and Raw values for Ice and Ore to current Ore Buyback sheet.

Renamed Ore Buyback to Buyback Values

Redesigned Buyback Values Sheet.

**Comment by gbrann** [comment]
Using `=IMPORTRANGE(Configuration!$B$2,"Buyback Values!D22")` where it pulls the sheet's ID number from a new tab called "Configuration", the second part of the formula pulls from the location specified on the Production workbook.

**Comment by gbrann** [comment]
Refining Yield Modifier * (1 + (Structure Bonus/100) * Structure Security Modifier * (1+ (Refining Skill level * .03)) * (1+ (Reprocessing Efficiency skill level * .02)) * (1+(Ore specific/ice processing skill level * .02)) * (1 + (Processing Implant Percentage/100))

**Comment by gbrann** [comment]
@wytsa We need the weight number in Participation to go off the values set in Configuration based on what ship they select in the drop down. Care to assist?

**Comment by wytsa** [comment]
formulas for "weight number in participation" has been set and tested for use.

**Comment by gbrann** [comment]
Released as EPS Buyback Module v1.0
