### ISSUE TITLE
BUG 1.1 - Corporate Stock for Capital Components not showing Required

### ISSUE THREAD

**Issue by gbrann** [gbrann/EVEProductionSuite#33]
=MAX(0,'Cap Build Requirement Backend'!CY2)

Shows all items 0 when there is need for them. 

CRITICAL BUG

**Comment by wytsa** [comment]
capital parts problem solved
=MAX(0,'Cap Build Requirement Backend'!CY2) changed to
=MAX(0,'Cap Build Requirement Backend'!$BW2)
formula was changed in the redesign of the sheet.

**Comment by gbrann** [comment]
Closed - Current DEV 1.1.2 to be released for bug fix.
