### ISSUE TITLE
CMM - Mineral to Ore Counts miscalculated

### ISSUE THREAD

**Issue by wytsa** [gbrann/EVEProductionSuite#47]
uncompressed/compressed values on back-end sheets miscalculated
more info to come

**Comment by FootyMD** [comment]
uncompressed ore is:

=SUM(D31/'Cap Build Requirement Backend'!AN23)

Should be

=SUM(D31/'Cap Build Requirement Backend'!AN23)*100


compressed ore is:

=roundup(SUM(D30/'Cap Build Requirement Backend'!AM24/100))


Should be:

=roundup(SUM(D30/'Cap Build Requirement Backend'!AM24))

**Comment by wytsa** [comment]
formulas for uncompressed ore has been changed to the correct formulas
compressed or formula references uncompressed ore value for calculations.

will start work on other backend tabs to finish fixing bug

**Comment by gbrann** [comment]
Ok, we are NOT doing this hot fix on 1.1.3 as it would be .. hell. 

We will push CMM and the Production Modules as quick as we can muster and go from there.

**Comment by wytsa** [comment]
ore counts on capital and citadel master sheets have been fixed and are in order for later changes.

**Comment by wytsa** [comment]
uncompressed formula has been changed to:
=SUM(D31/'Capital Backend'!BO23)*100

compressed formula has been changed to:
=roundup(SUM(B36/100))

this has currently fixed the present issue with the numbers.
