### ISSUE TITLE
CMM - background connectivity to all modules

### ISSUE THREAD

**Issue by wytsa** [gbrann/EVEProductionSuite#56]
**Reason for Dev Work**
When time allows we will need other "module" main pages made so that work can commence when CMM work stalls.

**Module**
CMM config tab
config tabs for all other modules

**Changes**
background connection to all other modules for future development

**Comment by gbrann** [comment]
Working on it! Doing accounting today, as we finish up the new backend pages. We need to get backend ready for production modules - once that is done, the rest is a breeze.

**Comment by gbrann** [comment]
Script ID data already being stored in CMM Configuration. Modulation is already ready.
