### ISSUE TITLE
Char Use (instead of corp use)

### ISSUE THREAD

**Issue by ericholzer** [gbrann/EVEProductionSuite#58]
Hi,
personally I have several char for production but not a single corp focused on this project

for me could be very useful to have the choice between:

a) corp data (like now)

b) personal data (for the chars authed)

could be possible?

**Comment by gbrann** [comment]
I'm sorry to say that it is never that nice and easy. 

This entire project is designed for corporations, and we have crafted the suite based on corporate ESI pulls. There are major differences between personal characters and corporations inside the ESI. 

This not a planned feature of this suite.
